# Generated by Django 3.2 on 2021-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210417_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Job Profile')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('location', models.CharField(blank=True, default='work from home', max_length=50, null=True, verbose_name='Location')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill Name')),
                ('rating', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advance')], max_length=1, verbose_name='Skill Rating')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='home.Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='home.Skill'),
        ),
    ]
